### PR TITLE
Differentiate between expected and unexpected EOFs in NgReader

### LINKED ISSUE #149: NgReader does not distinguish between expected and unexpected EOFs
`NgReader` currently returns `io.EOF` for both (a) expected EOFs between packets, and (b) when the file is unexpectedly truncated in the middle of a file. This is an issue because it makes it impossible to tell whether a pcap was incorrectly truncated (and therefore will not be accepted without error by tools like Wireshark).

The most obvious solution to this would be to edit `readBytes` to return `ErrUnexpectedEOF` (like `io.ReadFull`), and to also check the return of `Buffer.Discard` within `NgReader`. One potential issue with this is backwards compatibility: users of `gopacket` that expect the function to only return `EOF` would potentially crash. However, this is probably preferable to the current state where the errors are being silently ignored.

If backwards compatbility is critical, `NgReader` could also be modified to allow checking for another error through a new function, though this is probably a worse solution.

### PR DESCRIPTION
**Pull request by ericpauley**
Because `readBytes` and `Discard` were used in so many places it made more sense to have these return `UnexpectedEOF` and then explicitly downgrade this to `EOF` in the two places where it's expected (blank file and no bytes at start of block). Because of this second case it was necessary to have `readBytes` return the number of bytes read, which increased the number of lines changed.

I've expanded the test suite to cover these cases as well.

Fixes #149

### CODE REVIEW

File: pcapgo/ngread.go [hunk 1]
```diff
@@ -196,18 +217,18 @@ func (r *NgReader) readOption() error {
...
 		padding := length % 4
 		if padding > 0 {
 			padding = 4 - padding
-			if _, err := r.r.Discard(int(padding)); err != nil {
+			if err := r.discard(int(padding)); err != nil {
 				return err
 			}
 		}
-		r.currentBlock.length -= uint32(length + padding)
+		r.currentBlock.length -= uint32(length)
```
Comment (ericpauley) [inline pcapgo/ngread.go]: `discard` was previously only used by `_nrb`. Moved it to this file since it's used more generally and also adjusted consumers of `Discard` to account for the fact that `discard` also automatically subtracts padding from `currentBlock.length`
